--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: rwebsocket
    version: v1
  name: rwebsocket
spec: 
  ports: 
    - 
      name: http
      port: 8080
      targetPort: 8080
  selector: 
    app: rwebsocket
    version: v1
  type: NodePort
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: rwebsocket
    version: v1
  name: rwebsocket
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: rwebsocket
      version: v1
  template: 
    metadata: 
      labels: 
        app: rwebsocket
        version: v1
    spec: 
      containers: 
        - 
          image: "kapilshekharraina/rwebsocket"
          imagePullPolicy: IfNotPresent
          name: rwebsocket
          ports: 
          - containerPort: 8080    
          env:
            - name:  spring.profiles.active
              value: "sink"
          resources:
            requests:
                memory: "512Mi"
                cpu: "100m"
            limits:
                memory: "1024Mi"
                cpu: "400m"